name: Deploy to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to VM
        run: |
          # Replace with your actual script or commands to copy files to VM
          scp -r 'actions-runner' ec2-user@35.89.197.32:/Home/ec2-user/*
